### ISSUE TITLE
Instructions are not correct.

### ISSUE THREAD

**Issue by wjwieland** [BSFrance/BSFrance-avr#1]
The README is for the STM model of this board which is confusing.  Additionally, the readme talks about files that go into the hardware directory, what about those that go into the libraries directory?  These instructions do not reflect the directory structure on my setup of Arduino IDE(ver 1.8.5). Additionally, should not the zip file work with the 'Sketch Add ./Zip functionality in the IDE?

Please fix the documentation for this module.

**Comment by bot1131357** [comment]
Using Arduino IDE 1.8.7 on Windows 10, and it worked for me when I copied the files into `Documents\Arduino\hardware\BSFrance `

**Comment by wjwieland** [comment]
Thanks for the come-back.  Am glad it is working for you as you expect.  I am working on various Linux systems however, and there are clear differences. including a number of places where the BSFrance directory could be placed under /hardware, none of which work. I don't even own a windows machine, so that path will not work.  

Again, I thank you for getting back to me on the issue.
